workflows:
  build-android:
    name: Build Android
    environment:
      node: 20
      groups:
        - android_credentials
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          ls -F node_modules/expo
          cat package.json
      - name: Prebuild Android
        script: |
          cd frontend
          npx expo --version
          npx expo prebuild --clean --platform android
      - name: Build Android
        script: |
          sed -i "" '/enableBundleCompression/d' frontend/android/app/build.gradle
          cd frontend/android
          chmod +x gradlew
          ./gradlew bundleRelease assembleRelease
    artifacts:
      - frontend/android/app/build/outputs/bundle/release/*.aab
      - frontend/android/app/build/outputs/apk/release/*.apk

  build-ios:
    name: Build iOS
    environment:
      node: 20
      groups:
        - ios_credentials
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          rm -rf node_modules
          npm install
          cat package.json
      - name: Build iOS IPA
        script: |
          cd frontend
          npx expo export:ios --platform ios --type archive
    artifacts:
      - frontend/ios/build/*.ipa
